---
project_name: chrono

release:
    github:
        owner: gochrono
        name: chrono
    draft: true


build:
    main: main.go
    binary: chrono
    gcflags:
        - all=-trimpath={{.Env.GOPATH}}
    ldflags:
        - -s -w
        - -X github.com/gochrono/chrono/commands.version={{.Version}}
        - -X github.com/gochrono/chrono/commands.commit={{.ShortCommit}}
        - -X github.com/gochrono/chrono/commands.date={{.Date}}
    env:
        - CGO_ENABLED=0
    goos:
        - darwin
        - linux
        - windows
    goarch:
        - amd64
        - 386
    goarm:
        - 7

nfpm:
    formats:
        - deb
    vendor: "gochrono"
    homepage: "https://github.com/gochrono/chrono"
    maintainer: "Jordan Knott <jordan@jordanthedev.com>"
    description: "A fast and simple time tracker tool"
    license: "MIT"
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
        amd64: 64bit
        386: 32bit
        darwin: macOS
        linux: Linux
        windows: Windows

snapshot:
    name_template: SNAPSHOT-{{.Commit}}

checksum:
    name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    darwin: macOS
    linux: Linux
    windows: Windows
  files:
    - README.md
    - LICENSE
