# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
- repo: https://github.com/dnephin/pre-commit-golang
  sha: HEAD
  hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: go-unit-tests
